name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install snapd 
        run:  sudo apt install snapd -y
      - name: Uninstall snapd 
        run:  sudo apt autoremove --purge snapd -y
