
name: build
on:
  push:
  pull_request:
jobs:
  setupEvn:
    runs-on: self-hosted
    steps:
      - name: check /etc/sudoers
        run: echo ${{secrets.SUDOPASSWD}} | sudo -S whoami
      - name: check who is the user
        run: whoami
      - uses: actions/checkout@v2
      - name: Install software-properties-common
        run: echo ${{secrets.SUDOPASSWD}} | sudo -S apt-get install -y software-properties-common
      - name: Install python3
        run: echo ${{secrets.SUDOPASSWD}} | sudo -S apt-get install -y python3
      - name: Install python3-pip -y
        run: echo ${{secrets.SUDOPASSWD}} | sudo -S apt-get install python3-pip -y     
 
  test:
     runs-on: self-hosted
     needs: setupEvn
     steps:
      - name: run test 
        run: python3 test.py
  test2:
     runs-on: self-hosted
     needs: setupEvn
     steps:
      - name: run test 
        run: python3 test.py
  test3:
     runs-on: self-hosted
     needs: setupEvn
     steps:
      - name: run test 
        run: python3 test.py
        
  cleanup:
    needs: [test , test2, test3 ] 
    runs-on: self-hosted
    steps:
      - name: unInstall python3-pip 
        run: echo ${{secrets.SUDOPASSWD}} | sudo -S sudo apt-get autoremove --purge python3-pip -y 
      - name: uninstall python3
        run: echo ${{secrets.SUDOPASSWD}} | sudo -S sudo apt-get autoremove --purge python3 -y   
      - name: Uninstall software-properties-common
        run: echo ${{secrets.SUDOPASSWD}} | sudo -S apt-get autoremove --purge software-properties-common -y


 
