name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install snapd 
        run:  echo ${{secrets.SUDOPASSWD}}| sudo -S apt install snapd -y
      - name: Uninstall snapd 
        run:  echo ${{secrets.SUDOPASSWD}}| sudo -S apt autoremove --purge snapd -y
